name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "50 * * * *"
  push:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@v3.16
        with:
          token: ${{ secrets.My_Page}}
          filename: static/github-metrics.*
          config_padding: 0, 20
          committer_message: "chore: update github metrics [skip ci]"

          # Options
          user: Yutong-Zhou-cv
          template: classic
          config_timezone: Asia/Tokyo
          config_display: large


          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section

          plugin_stars: yes
          plugin_stars_limit: 4 # Limit to 4 entries

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year

          # languages
          plugin_languages: yes
          plugin_languages_ignored: "HTML"
